<title>Brookfield Chiropractor, New Berlin, Wauwatosa, WI</title>

  <meta name="description" content="">
  <meta name="keywords" content="">

<?php
include 'includes/header.php';
?>


<body>
    
<h1 id="main-header">Doctors vs. Chiropractors</h1>
    
    <div id="secondary-content">
        
         <div class="row">
            
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">

                <p>Your notion of a “real” doctor probably conforms to a prototype generated by the mass media.</p>
                
                <p>Many have come to think of a doctor as someone who prescribes advice and drugs or performs surgery. Sporting a white lab coat or surgical scrubs with a stethoscope at the neck, doctors are seen as all-knowing, omnipotent and able to save patients in 60 minutes, less commercials.</p>
        
                <p>A medical doctor (MD) and a chiropractor (DC) while different, have both received a degree from a government accredited medical school or chiropractic college and are licensed to practice..</p>
                
                <p>But that’s where the similarity ends because each discipline looks at health and healing in very different ways.</p>
                
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                
               <img src="images/apples-oranges-scale.jpg" alt="Scale" class="interior-img" />
                <figcaption>Comparing chiropractors and medical doctors is like trying to compare apples and oranges.</figcaption>
            
            </div>
            
        </div>
        
       <div class="row">
        
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                
                <p class="comparison">Medical Doctors</p>
                
                <ul>
                    <li>Sees the disease</li>
                    <li>Studies the blood</li>
                    <li>Relies on drugs</li>
                    <li>Treats symptoms</li>
                </ul>
            
            </div>
           
             <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                
                <p class="comparison">Chiropractors</p>
                
                <ul>
                    <li>Sees the person with the disease</li>
                    <li>Improves nervous system integrity</li>
                    <li>Reduces causes of nerve interference</li>
                    <li>Promotes proper bodily function</li>
                </ul>
            
            </div>
        
        </div>
        
        <br>
        
        <p>Clearly, these are two very different philosophies. Yet, each has its place. If you have broken bones or you’re bleeding by the side of the road, you want the heroic lifesaving measures of emergency medical treatment. But if you have chronic aches and pains or an interest in wellness, you may want the health restoration possible that is the focus of chiropractic care.</p>
        
</div>
            
    <div id="appointment">
    
        <h1 id="schedule">Schedule An Adjustment</h1>

            <a href="https://www.mychirotouch.com/SelfScheduler/index.aspx?clientid=BC0078" target="_blank"><div class="book-now">

                <span>BOOK NOW</span>

            </div></a>
    
    </div>


    <div id="additional-info">
        
        <div class="row">
            
            <div class="col-lg-6 col-md-6 col-sm-12 accordion">
                
               <?php
                    include 'includes/accordion.html';
                ?>
                
                   <script>
                        var acc = document.getElementsByClassName("accordion");
                        var i;

                        for (i = 0; i < acc.length; i++) {
                          acc[i].onclick = function() {
                            this.classList.toggle("active");
                            var panel = this.nextElementSibling;
                            if (panel.style.maxHeight){
                              panel.style.maxHeight = null;
                            } else {
                              panel.style.maxHeight = panel.scrollHeight + "px";
                            } 
                          }
                        }
                    </script>

            </div>
            
            
            <div class="col-lg-6 col-md-6 col-sm-12">
                
                <table>
                    <h4>Office Hours</h4>
                  <tr>
                    <th>Day</th>
                    <th>Morning</th> 
                    <th>Afternoon</th>
                  </tr>
                  <tr class="lightgray">
                    <td>M</td>
                    <td>-------</td>
                    <td>1:30 - 5:30</td>
                  </tr>
                  <tr>
                    <td>T</td>
                    <td>7:30 - 12:00 </td>
                    <td>-------</td>
                  </tr>
                  <tr class="lightgray">
                    <td>W</td>
                    <td>8:00 - 12:00 </td>
                    <td>2:00 - 6:00 </td>
                  </tr>
                    <tr>
                    <td>T</td>
                    <td>-------</td>
                    <td>1:30 - 5:30 </td>
                  </tr>
                    <tr class="lightgray">
                    <td>F</td>
                    <td>8:00 - 12:00</td>
                    <td>-------</td>
                  </tr>
                </table>
                    <a href="tel:262-754-5500" class="table-phonenumber"><h4>(262) 754-5500</h4></a>
                
                <img src="images/wi_milwaukee_chiropractors_2018.png" alt="Best Chiropractors in Milwaukee" id="expertise" />
                
            </div>
        
        </div>
        
    </div>
        
</body>

<?php
include 'includes/footer.php';
?>