<title>Brookfield Chiropractor, New Berlin, Wauwatosa, WI</title>

  <meta name="description" content="">
  <meta name="keywords" content="">

<?php
include 'includes/header.php';
?>

<body>
    
<h1 id="main-header">Privacy Policy</h1>
    
    <div id="secondary-content">
        
        <p>This Privacy Policy applies to the Brookfield Chiropractic website. The Brookfield Chiropractic website is provided for information and educational purposes and may contain links to other sites. Once you enter another website (whether through an advertisement, service, or content link), be aware that Brookfield Chiropractic is not responsible for the privacy practices of such other sites. We encourage you to look for and review the privacy statements of each and every website that you visit.</p>
        
        <h3 class="subheader">Personal Information We Collect from You</h3>
        
        <p>We collect the following personal information from you on the Brookfield Chiropractic website forms.</p>
        
        <ul>
            <li>First and Last name</li>
            <li>Email address</li>
            <li>Phone number</li>     
        </ul>
    
        <p>By entering this information, you are providing personal information that will be used by Brookfield Chiropractic for the sole purpose of scheduling your appointment or returning your contact request.</p>
        
        <p>If you choose to enroll as a subscriber of our website, you will receive recurring practice newsletters, announcements and occasional promotional information via email. These emails will be of a general nature and will in no way disclose your unique health characteristics. At the time you subscribe or any time thereafter, you can choose to opt-out of receiving these emails from us.</p>
        
        <p>To subscribe to our website, we need certain contact information, such as your name and email address. At your option, you may also provide demographic information (such as gender or age) about yourself, but it is not required. You can unsubscribe from the newsletters by simply clicking on the “unsubscribe” link at the bottom of our emails; you will be immediately unsubscribed.</p>
        
        <p>We are committed to protecting the privacy of children. Neither Brookfield Chiropractic nor any of its services are designed or intended to attract children under the age of 13.</p>
        
        <h3 class="subheader">Passive Information We Collect</h3>
        
        <p>Like many other websites, we also automatically collect and log other non-identifying information when you interact with the Brookfield Chiropractic website:</p>
        
        <p>Device data. We collect data from the device and application you use to access the Brookfield Chiropractic website, such as your Internet protocol (IP) addresses, operating system, device type, browser type and timestamps.</p>
        
        <p>Usage data. We collect usage data that may include which Brookfield Chiropractic webpages you visit, what you click on, when you performed those actions, and so on. Emails sent by Brookfield Chiropractic collect information about who opened those emails and clicked on links in them. We do this to measure the performance of the Brookfield Chiropractic email messaging and to monitor and improve email deliverability and open rates.</p>
        
        <p>Google Analytics. In addition, our website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). The information generated by the cookie about your use of our website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of our website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google’s behalf. Google will not associate your IP address with any other data held by Google. Further information may be obtained by visiting Google’s privacy policy.</p>
        
        <p>We use this information to conduct research and analysis to better understand how visitors are using the Brookfield Chiropractic website, so that we can improve our website experience. From time to time, Brookfield Chiropractic or it’s operations contractors acting on their behalf, conduct online research in order to gather feedback about our site through online or email surveys.</p>
        
        <p>Participation in these surveys is completely voluntary and you may choose whether or not to participate and disclose information. Personally Identifiable Information collected through market research will only be used by Brookfield Chiropractic and its operations contractors and will never be given or sold to a third party.</p>
        
        <h3 class="subheader">Disclosure of Your Information</h3>
        
        <p>Except as set forth in this Privacy Policy or as specifically agreed to by you, Brookfield Chiropractic will not disclose any Personally Identifiable or Personal Health Information it gathers from you on our website. We will only release Personally Identifiable or Personal Health Information to third parties:</p>
        
        <p>(i) to comply with valid legal requirements such as a law, regulation, search warrant, subpoena or court order.</p>
        
        <p>(ii) in special cases, such as a physical threat to you or others. In the event that we are legally compelled to disclose your Personally Identifiable or Personal Health Information to a third party, we will attempt to notify you unless doing so would violate the law or court order.</p>
        
        <h3 class="subheader">Changes to this Privacy Policy</h3>
        
        <p>We will inform you if a material change to the Privacy Policy is made that involves the use of your Personally Identifiable Information. Your continued use of the Brookfield Chiropractic site will indicate acceptance of the changes. Please exit the site immediately if you do not agree to the terms of this Privacy Policy or any revised policy.</p>
        
        <p>This Privacy Policy does not protect you when you send content, questions or ideas to Brookfield Chiropractic via email. If you want to keep them private or proprietary, do not send them in an email. We try to answer every email within 48 business hours, but are not always able to do so.</p>
        
        <p>Last Updated: January 2018</p>
        
    </div>



</body>

<?php
include 'includes/footer.php';
?>